### ISSUE TITLE
No module named 'klayout.lay'

### ISSUE THREAD

**Issue by ooksang** [klayoutmatthias/canvas2canvas#2]
I followed the instruction of canvas2canvas guide.
I downloaded git file from 'https://github.com/KLayout/klayout'
and run '$ python3 setup.py build'. 

After setup, run the './server.py' 
I saw error message 'No module named 'klayout.lay'.

When I checked my python>site-packages>klayout folder, there is no 'lay' folder inside.
I  can import 'klayout.db' but can not import  'klayout.lay'.

Is there something to do for installation?

Thanks

**Comment by klayoutmatthias** [comment]
"build" will not install the module, but rather create them. 
In order to use them, I have to use:

```
PYTHONPATH=build/lib.linux-x86_64-3.10 python3
Python 3.10.5 (main, Jun  8 2022, 09:26:22) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import klayout.lay
...
```

The exact path be different in your case.

You can install the new module system-wide (I'd no recommend that) using

```
python3 setup.py install
```

You can also generate a .whl or .egg file for distribution

```
python3 setup.py bdist_wheel
python3 setup.py bdist
```

This produces the files in the "dist" directory.

**Comment by ooksang** [comment]
> 

Thank you for you help!

As I understood, It means I have to add new path for klayout module generated after running 'build.sh'.
I have few more questions.

1. There is no lib file.
After running build.sh, I saw 'build-release' folder. There are many libraries of klayout but python library.

2. How I build.
I used below command. There is no static library in my python folder, I assigned dynamic file 'libpython3.9.so.1.0'.
So, It is possible to run 'build.sh'.
> (klayoutweb) [ooksangyoo@LGDADPVM009 klayout-qtless-canvas2]$ ./build.sh 
-python /data001/dlpusers/ooksangyoo/anaconda3/bin/python 
-pylib /data001/dlpusers/ooksangyoo/anaconda3/lib/libpython3.9.so.1.0

But, Errors occurred. I attached build message.

> /data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif/../../../libklayout_pya.so: undefined reference to `PyDescr_NewGetSet'
/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif/../../../libklayout_pya.so: undefined reference to `PyByteArray_AsString'
/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif/../../../libklayout_pya.so: undefined reference to `PyBytes_FromStringAndSize'
/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif/../../../libklayout_pya.so: undefined reference to `PyWeakref_NewRef'
collect2: error: ld returned 1 exit status
gmake[3]: *** [../../../../build-release/strm2cif] error 1
gmake[3]: Leaving directory `/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif'
gmake[2]: *** [sub-strm2cif-make_default] error 2
gmake[2]: Leaving directory `/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src'
gmake[1]: *** [sub-src-make_default] error 2
gmake[1]: Leaving directory `/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies'
gmake: *** [sub-buddies-make_default] error 2

Anyway, I could get klayout libraries in 'build-release'. So I tried to run python like your comment.
> PYTHONPATH=build-release python3

But, I couldn't import 'klayout.lay'.

**Comment by ooksang** [comment]
[>]

 Thank you for you help!

As I understood, It means I have to add new path for klayout module generated after running 'build.sh'. I have few more questions.
 
1. There is no lib file.
   After running build.sh, I saw 'build-release' folder. There are many libraries of klayout but python library.
2. How I build.
   I used below command. There is no static library in my python folder, I assigned dynamic file 'libpython3.9.so.1.0'.
   So, It is possible to run 'build.sh'.
 
```
(klayoutweb) [ooksangyoo@LGDADPVM009 klayout-qtless-canvas2]$ ./build.sh
 -python /data001/dlpusers/ooksangyoo/anaconda3/bin/python
 -pylib /data001/dlpusers/ooksangyoo/anaconda3/lib/libpython3.9.so.1.0
```
 
But, Errors occurred. I attached build message.
``` 
 /data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif/../../../libklayout_pya.so: undefined reference to `PyDescr_NewGetSet' /data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif/../../../libklayout_pya.so: undefined reference to `PyByteArray_AsString'
 /data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif/../../../libklayout_pya.so: undefined reference to `PyBytes_FromStringAndSize' /data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif/../../../libklayout_pya.so: undefined reference to `PyWeakref_NewRef'
collect2: error: ld returned 1 exit status
gmake[3]: *** [../../../../build-release/strm2cif] error 1
gmake[3]: Leaving directory `/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src/strm2cif' gmake[2]: *** [sub-strm2cif-make_default] error 2 gmake[2]: Leaving directory `/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies/src'
gmake[1]: *** [sub-src-make_default] error 2
gmake[1]: Leaving directory `/data001/dlpusers/ooksangyoo/download/klayout-qtless-canvas2/build-release/buddies'
gmake: *** [sub-buddies-make_default] error 2
```
Anyway, I could get klayout libraries in 'build-release'. So I tried to run python like your comment.
``` 
PYTHONPATH=build-release python3
```

But, I couldn't import 'klayout.lay'.


[issue2-5.txt](https://github.com/klayoutmatthias/canvas2canvas/files/9295193/issue2-5.txt)
![issue2-4](https://user-images.githubusercontent.com/30854992/183780565-5d6d2646-7154-41c4-8a5d-c0c1e3ae627b.png)
![issue2-5](https://user-images.githubusercontent.com/30854992/183780574-dcfc8ba2-f863-4dac-8d96-1b69e20a0eee.png)
![issue2-6](https://user-images.githubusercontent.com/30854992/183780576-16fb6b50-22ac-4ccc-bcda-3c99184f8f6e.png)

**Comment by klayoutmatthias** [comment]
"build.sh" will build the KLayout binary. This is the application, not the Python module.

If you only want to use the Python module, go ahead with the previous way - i.e. using `python3 setup.py build` and follow the instructions I gave above.

For compiling the actual application you'll need a number of development packages installed on Linux. The exact list depends on the Linux distribution you're using. For more details see here: https://www.klayout.de/build.html

Matthias
